import { parseLinkedInConnections } from '../csv';

describe('parseLinkedInConnections', () => {
  it('parses LinkedIn CSV rows into connection objects', () => {
    const csv = `First Name,Last Name,URL,Email Address,Company,Position,Connection on,Location
Alex,Smith,https://www.linkedin.com/in/alex-smith,alex@example.com,Acme,Product Manager,1/1/2024,"New York, NY"
"Jamie","Doe","https://www.linkedin.com/in/jamie-doe","jamie@example.com","Data Co","Director, Analytics","2/2/2024","San Francisco, CA"`;

    const connections = parseLinkedInConnections(csv);
    expect(connections).toHaveLength(2);
    expect(connections[0]).toMatchObject({
      firstName: 'Alex',
      lastName: 'Smith',
      url: 'https://www.linkedin.com/in/alex-smith',
      email: 'alex@example.com',
      company: 'Acme',
      position: 'Product Manager',
    });
    expect(connections[1].position).toBe('Director, Analytics');
    expect(connections[1].location).toBe('San Francisco, CA');
  });

  it('finds the header within the first five rows and matches names case-insensitively', () => {
    const csv = `Report generated by LinkedIn
for account sample@example.com

FIRST NAME,last NAME,url,email ADDRESS,company,POSITION,connected ON,location
Taylor,Jones,https://www.linkedin.com/in/taylor-jones,taylor@example.com,Example Corp,Engineer,3/3/2024,Austin, TX`;

    const connections = parseLinkedInConnections(csv);
    expect(connections).toHaveLength(1);
    expect(connections[0]).toMatchObject({
      firstName: 'Taylor',
      lastName: 'Jones',
      url: 'https://www.linkedin.com/in/taylor-jones',
      email: 'taylor@example.com',
      company: 'Example Corp',
      position: 'Engineer',
      connectedOn: '3/3/2024',
    });
  });
});
