import {
  AI_CAPABILITIES,
  AI_RESISTANT_CHARACTERISTICS,
  AI_SKILL_STACK,
  AI_TOOLS_BY_DOMAIN,
  CATEGORY_AI_ANALYSIS,
  CATEGORY_SIGNALS,
  FORMAL_EDUCATION_OPTIONS,
  KEYWORD_RULES,
  LOW_COST_OPTIONS,
  MARKET_VALIDATED_RESOURCES,
} from '../data/constants';
import {
  CareerGoal,
  CareerPathTier,
  CipherReport,
  LinkedInConnection,
  MarketSnapshot,
  NetworkReport,
  ReportSection,
  SkillInput,
  SkillInsight,
  SkillCategory,
  UserProfile,
} from '../types';

const clamp = (value: number, min = 1, max = 10) => Math.min(max, Math.max(min, value));

const scoreToLabel = (value: number) => {
  if (value >= 8) return 'High';
  if (value >= 5) return 'Medium';
  return 'Low';
};

const getKeywordSignals = (name: string) => {
  const lower = name.toLowerCase();
  const matches = KEYWORD_RULES.filter((rule) =>
    rule.keywords.some((keyword) => lower.includes(keyword))
  );

  if (matches.length === 0) {
    return {
      adjust: {},
      aiRisk: undefined,
      timeline: undefined,
      tools: [] as string[],
    };
  }

  return matches.reduce(
    (acc, match) => ({
      adjust: {
        demand: (acc.adjust.demand || 0) + (match.adjust.demand || 0),
        scarcity: (acc.adjust.scarcity || 0) + (match.adjust.scarcity || 0),
        compPremium: (acc.adjust.compPremium || 0) + (match.adjust.compPremium || 0),
        futureProof: (acc.adjust.futureProof || 0) + (match.adjust.futureProof || 0),
      },
      aiRisk: match.aiRisk || acc.aiRisk,
      timeline: match.timeline || acc.timeline,
      tools: [...acc.tools, ...(match.tools || [])],
    }),
    {
      adjust: {},
      aiRisk: undefined as undefined | SkillInsight['aiRisk'],
      timeline: undefined as undefined | string,
      tools: [] as string[],
    }
  );
};

const resolveToolsByDomain = (skillName: string) => {
  const lower = skillName.toLowerCase();
  if (lower.includes('marketing')) return AI_TOOLS_BY_DOMAIN.Marketing;
  if (lower.includes('sales')) return AI_TOOLS_BY_DOMAIN.Sales;
  if (lower.includes('engineer') || lower.includes('developer') || lower.includes('software'))
    return AI_TOOLS_BY_DOMAIN.Engineering;
  if (lower.includes('design') || lower.includes('ux') || lower.includes('ui'))
    return AI_TOOLS_BY_DOMAIN.Design;
  if (lower.includes('finance') || lower.includes('accounting'))
    return AI_TOOLS_BY_DOMAIN.Finance;
  if (lower.includes('legal') || lower.includes('compliance')) return AI_TOOLS_BY_DOMAIN.Legal;
  if (lower.includes('health') || lower.includes('clinical'))
    return AI_TOOLS_BY_DOMAIN.Healthcare;
  if (lower.includes('hr') || lower.includes('recruit')) return AI_TOOLS_BY_DOMAIN.HR;
  if (lower.includes('operations') || lower.includes('supply'))
    return AI_TOOLS_BY_DOMAIN.Operations;
  return [];
};

const buildSkillInsight = (skill: SkillInput): SkillInsight => {
  const base = CATEGORY_SIGNALS[skill.category];
  const keywordSignals = getKeywordSignals(skill.name);
  const demand = clamp(base.demand + (keywordSignals.adjust.demand || 0));
  const scarcity = clamp(base.scarcity + (keywordSignals.adjust.scarcity || 0));
  const compPremium = clamp(base.compPremium + (keywordSignals.adjust.compPremium || 0));
  const futureProof = clamp(base.futureProof + (keywordSignals.adjust.futureProof || 0));

  const marketValueScore = Math.round(
    (demand + scarcity + compPremium + futureProof) * 2 +
      Math.min(skill.years, 10) +
      skill.enjoyment
  );

  const aiRisk = keywordSignals.aiRisk || base.aiRisk;
  const aiImpactTimeline = keywordSignals.timeline || base.timeline;
  const analysis = CATEGORY_AI_ANALYSIS[skill.category];
  const aiTools = Array.from(
    new Set([...keywordSignals.tools, ...resolveToolsByDomain(skill.name)])
  );

  const aiResistantSignals =
    skill.category === 'soft/interpersonal' || skill.category === 'leadership'
      ? AI_RESISTANT_CHARACTERISTICS
      : AI_RESISTANT_CHARACTERISTICS.filter((item) =>
          ['accountability', 'trust', 'relational', 'vision'].some((keyword) =>
            item.toLowerCase().includes(keyword)
          )
        );

  const riskReasoning =
    aiRisk === 'High' || aiRisk === 'Very High'
      ? 'Core tasks are increasingly automated or generated by AI systems.'
      : aiRisk === 'Moderate'
        ? 'AI can augment routine tasks, but judgment and context still matter.'
        : 'Human judgment, trust, and accountability keep this resilient.';

  const projections = {
    threeYear:
      aiRisk === 'High' || aiRisk === 'Very High'
        ? 'Demand may compress; AI-augmented practitioners will retain premium roles.'
        : 'Demand likely stable to growing with AI-enabled workflows.',
    fiveYear:
      aiRisk === 'High' || aiRisk === 'Very High'
        ? 'Expect role redesign toward oversight, QA, and human-in-the-loop work.'
        : 'Expect expanding scope and higher leverage with AI tooling.',
    tenYear:
      aiRisk === 'High' || aiRisk === 'Very High'
        ? 'Skill must evolve into adjacent AI-resistant competencies.'
        : 'Skill remains valuable with emphasis on strategy and cross-domain synthesis.',
  };

  return {
    name: skill.name,
    category: skill.category,
    marketValueScore,
    demandLevel: scoreToLabel(demand),
    scarcity: scoreToLabel(scarcity),
    compensationPremium: scoreToLabel(compPremium),
    futureProofing: scoreToLabel(futureProof),
    aiRisk,
    aiImpactTimeline,
    aiRiskReasoning: riskReasoning,
    aiCan: analysis.aiCan,
    aiCannot: analysis.aiCannot,
    aiTools,
    transformation: analysis.transformation,
    humanEdge: analysis.humanEdge,
    valueMaintenance: [
      'Pair this skill with AI tooling and workflow automation.',
      'Document outcomes to show measurable impact beyond task execution.',
      'Build cross-domain fluency so you can frame problems, not just solve them.',
      'Monitor AI capability shifts and update your tool stack quarterly.',
      'Develop adjacent AI-resistant skills that raise your strategic scope.',
    ],
    aiResistantSignals,
    projections,
  };
};

const inferIndustryFromTitle = (title: string) => {
  const lower = title.toLowerCase();
  if (lower.includes('engineer') || lower.includes('developer')) return 'Technology';
  if (lower.includes('designer') || lower.includes('ux')) return 'Design';
  if (lower.includes('marketing')) return 'Marketing';
  if (lower.includes('sales')) return 'Sales';
  if (lower.includes('finance') || lower.includes('account')) return 'Finance';
  if (lower.includes('nurse') || lower.includes('clinical')) return 'Healthcare';
  if (lower.includes('legal') || lower.includes('attorney')) return 'Legal';
  if (lower.includes('product')) return 'Product';
  if (lower.includes('hr') || lower.includes('recruit')) return 'HR';
  return 'Other';
};

const inferSeniority = (title: string) => {
  const lower = title.toLowerCase();
  if (lower.includes('chief') || lower.includes('cxo') || lower.includes('vp'))
    return 'Executive';
  if (lower.includes('director') || lower.includes('head')) return 'Director';
  if (lower.includes('manager') || lower.includes('lead')) return 'Manager';
  if (lower.includes('senior') || lower.includes('sr')) return 'Senior';
  if (lower.includes('intern') || lower.includes('junior') || lower.includes('associate'))
    return 'Entry';
  return 'Mid-level';
};

const buildNetworkReport = (connections: LinkedInConnection[]): NetworkReport => {
  const totalConnections = connections.length;
  const industryCount = new Map<string, number>();
  const seniorityCount = new Map<string, number>();
  const companyCount = new Map<string, number>();
  const locationCount = new Map<string, number>();

  connections.forEach((connection) => {
    const industry = inferIndustryFromTitle(connection.position || '');
    industryCount.set(industry, (industryCount.get(industry) || 0) + 1);

    const seniority = inferSeniority(connection.position || '');
    seniorityCount.set(seniority, (seniorityCount.get(seniority) || 0) + 1);

    if (connection.company) {
      companyCount.set(connection.company, (companyCount.get(connection.company) || 0) + 1);
    }

    if (connection.location) {
      locationCount.set(connection.location, (locationCount.get(connection.location) || 0) + 1);
    }
  });

  const toBreakdown = (map: Map<string, number>, limit = 6) =>
    Array.from(map.entries())
      .sort((a, b) => b[1] - a[1])
      .slice(0, limit)
      .map(([name, count]) => `${name}: ${count}`);

  const hiringManagers = connections
    .filter((connection) =>
      ['director', 'vp', 'head', 'chief'].some((keyword) =>
        connection.position.toLowerCase().includes(keyword)
      )
    )
    .slice(0, 8)
    .map((connection) => `${connection.firstName} ${connection.lastName}`.trim());

  const recruiters = connections
    .filter((connection) =>
      ['recruit', 'talent', 'people'].some((keyword) =>
        connection.position.toLowerCase().includes(keyword)
      )
    )
    .slice(0, 8)
    .map((connection) => `${connection.firstName} ${connection.lastName}`.trim());

  const warmIntroductions = connections
    .filter((connection) => connection.company && connection.position)
    .slice(0, 8)
    .map((connection) => `${connection.company} - ${connection.position}`);

  return {
    totalConnections,
    industryBreakdown: toBreakdown(industryCount),
    seniorityBreakdown: toBreakdown(seniorityCount),
    companyBreakdown: toBreakdown(companyCount),
    geographyBreakdown: toBreakdown(locationCount),
    hiringManagers: hiringManagers.length
      ? hiringManagers
      : ['Add LinkedIn data to surface hiring managers.'],
    recruiters: recruiters.length ? recruiters : ['Add LinkedIn data to surface recruiters.'],
    warmIntroductions: warmIntroductions.length
      ? warmIntroductions
      : ['Add LinkedIn data to surface warm introductions.'],
    gaps: [
      'Identify missing seniority levels in target industry.',
      'Add more connections at hiring manager and recruiter levels.',
      'Increase representation in target companies and regions.',
    ],
    actionPlan: [
      'Reach out to top 5 hiring managers for informational interviews.',
      'Request warm introductions to target companies.',
      'Build a weekly networking cadence (2-3 new connections per week).',
    ],
  };
};

const buildMarketSnapshot = (market: MarketSnapshot): ReportSection => {
  const warnings = [];
  if (!market.updatedAt) warnings.push('Add the date of your latest market scan.');
  if (!market.sources) warnings.push('Include sources like BLS, LinkedIn, or WEF reports.');

  return {
    id: 'market-snapshot',
    title: 'Market Snapshot',
    summary:
      market.indicators ||
      'No real-time indicators provided yet. Cipher needs current market inputs to tailor advice.',
    bullets: [
      market.hiringTrends
        ? `Hiring trends: ${market.hiringTrends}`
        : 'Hiring trends: Add notes on hiring vs. freezes.',
      market.layoffs ? `Layoffs: ${market.layoffs}` : 'Layoffs: Add recent layoff signals.',
      market.funding ? `Funding and M&A: ${market.funding}` : 'Funding: Add recent funding data.',
      market.aiTrends
        ? `AI-related trends: ${market.aiTrends}`
        : 'AI trends: Add AI hiring or automation signals.',
      market.sources ? `Sources: ${market.sources}` : 'Sources: Add trusted data sources.',
      ...warnings,
    ],
  };
};

const buildDemographicStrategy = (profile: UserProfile): ReportSection => {
  const age = parseInt(profile.age, 10);
  const ageInsight = Number.isNaN(age)
    ? 'Age data not provided yet.'
    : age < 30
      ? 'Lean into fast learning signals, portfolio proof, and rapid iteration.'
      : age < 45
        ? 'Balance depth with agility; highlight measurable outcomes and leadership moments.'
        : 'Position experience as a strategic asset while staying current on AI tools.';

  return {
    id: 'demographic-strategy',
    title: 'Demographic Strategy',
    summary:
      'Cipher factors demographic realities to provide realistic, tactical guidance without discouragement.',
    bullets: [
      `Age guidance: ${ageInsight}`,
      profile.gender
        ? `Gender strategy: Seek employers with strong DEI metrics and visible leadership diversity.`
        : 'Gender strategy: Add gender data to tailor DEI and negotiation guidance.',
      profile.raceEthnicity
        ? `Race/ethnicity strategy: Leverage affinity networks, ERGs, and inclusive employers.`
        : 'Race/ethnicity strategy: Add data to tailor network and employer targeting.',
      'Target companies known for inclusive hiring and transparent promotion pathways.',
      'Use compensation benchmarks to reduce negotiation bias.',
    ],
  };
};

const buildAIForward = (skills: SkillInput[], goals: CareerGoal[]): ReportSection => {
  const skillNames = skills.map((skill) => skill.name.toLowerCase());
  const hasTechnical = skills.some((skill) => skill.category === 'technical');
  const hasProduct = skillNames.some((name) => name.includes('product'));
  const hasOps = skillNames.some((name) => name.includes('operations') || name.includes('process'));
  const hasSales = skillNames.some((name) => name.includes('sales'));
  const hasDesign = skillNames.some((name) => name.includes('design') || name.includes('ux'));
  const hasPolicy = skillNames.some((name) => name.includes('policy') || name.includes('legal'));

  const roles = [
    hasTechnical && 'AI/ML Engineering or Applied AI Engineering',
    hasProduct && 'AI Product Management',
    hasPolicy && 'AI Ethics and Governance',
    hasOps && 'AI Implementation Specialist',
    hasSales && 'AI Sales and Solutions',
    hasDesign && 'Human-AI Interaction Design',
  ].filter(Boolean) as string[];

  const businessIdeas = [
    'AI workflow audits for your industry to identify automation ROI.',
    'AI-enabled consulting for compliance, risk, or operations.',
    'Custom AI toolkits or prompt libraries tailored to your domain.',
    'Picks-and-shovels services for AI teams (data prep, evaluation, QA).',
  ];

  const stack = AI_SKILL_STACK.flatMap((layer) => [
    `${layer.layer}: ${layer.items.join(', ')}`,
  ]);

  const toolBullets = Object.entries(AI_TOOLS_BY_DOMAIN).map(
    ([domain, tools]) => `${domain}: ${tools.join(', ')}`
  );

  return {
    id: 'ai-forward',
    title: 'AI-Forward Opportunities',
    summary:
      'Focus on becoming an AI-augmented professional rather than competing against automation.',
    bullets: [
      roles.length
        ? `AI advancement roles: ${roles.join('; ')}.`
        : 'AI advancement roles: Add more technical or product signals to unlock tailored roles.',
      `AI business opportunities: ${businessIdeas.join(' ')}`,
      `AI skill stack: ${stack.join(' | ')}`,
      `Tools to master: ${toolBullets.join(' | ')}`,
      goals.includes('Entrepreneurship')
        ? 'Entrepreneurial focus detected: prioritize AI consulting MVP and first paying clients.'
        : 'Entrepreneurial option: consider side projects that validate AI-driven services.',
    ],
  };
};

const buildCareerPaths = (profile: UserProfile, topSkills: SkillInsight[]): CareerPathTier[] => {
  const baseRole = profile.currentRole || 'your current role';
  const mainSkill = topSkills[0]?.name || 'core strengths';

  return [
    {
      tier: 'Tier 1: Traditional Path',
      title: `Advance in ${baseRole}`,
      overview: `Follow the established ladder in ${baseRole}, emphasizing ${mainSkill}.`,
      riskReward: 'Lower risk, predictable growth, strong benefits.',
      earningPotential: 'Steady increases with clear promotion milestones.',
      threeYearPlan: {
        year1: [
          'Target next-level roles and document measurable wins.',
          'Close any role-critical skill gaps.',
          'Build relationships with hiring managers in your function.',
        ],
        year2: [
          'Seek stretch projects that expand scope.',
          'Develop leadership or ownership opportunities.',
          'Publish or present internal case studies.',
        ],
        year3: [
          'Pursue senior or lead roles with larger ownership.',
          'Negotiate compensation using outcome-based evidence.',
          'Mentor junior peers to signal leadership readiness.',
        ],
      },
      fiveYearPlan: {
        year4: [
          'Decide between management or expert track.',
          'Build a personal brand inside and outside the company.',
        ],
        year5: [
          'Target director-level roles or principal specialist roles.',
          'Explore additional income streams (consulting, teaching).',
        ],
      },
      learningPath: [
        'Role-specific certifications with market demand.',
        'Advanced AI literacy to augment daily workflows.',
        'Leadership and stakeholder management development.',
      ],
      projects: [
        'High-visibility projects tied to revenue or cost savings.',
        'Cross-functional initiatives that showcase collaboration.',
      ],
      earningsStrategy: [
        'Benchmark compensation quarterly and negotiate at promotion windows.',
        'Use competing offers only when strategically aligned.',
      ],
      examples: [
        'Add a verified real-world example with a source link.',
        'Example should include name, role change, and outcome.',
      ],
      differentials: [
        'Compensation differential: baseline market growth rate.',
        'Timeline differential: steady 12-24 month promotion cycles.',
        'Effort differential: moderate intensity with predictable workload.',
        'Optionality: keeps options open across similar employers.',
      ],
      aiResilience: 'High resilience when paired with AI tool adoption.',
    },
    {
      tier: 'Tier 2: Off-the-Beaten-Path',
      title: `Hybrid pivot combining ${mainSkill} with adjacent roles`,
      overview:
        'Leverage transferable skills to move into adjacent, faster-growing roles.',
      riskReward: 'Moderate risk, accelerated growth potential.',
      earningPotential: 'Higher upside if pivot succeeds; requires proof of competence.',
      threeYearPlan: {
        year1: [
          'Identify adjacent roles with faster growth and skill overlap.',
          'Build a portfolio that proves readiness for the pivot.',
          'Secure mentors in the target field.',
        ],
        year2: [
          'Make a lateral move or bridge role transition.',
          'Own projects that showcase hybrid skill value.',
          'Expand network in the target industry.',
        ],
        year3: [
          'Target senior roles in the new track.',
          'Establish thought leadership via talks or writing.',
        ],
      },
      fiveYearPlan: {
        year4: [
          'Consider leadership roles in the new function.',
          'Explore specialized niches with scarce talent.',
        ],
        year5: [
          'Target lead or principal roles with high autonomy.',
          'Build optionality for consulting or entrepreneurship.',
        ],
      },
      learningPath: [
        'Skill-bridge credentials with strong job posting demand.',
        'Hands-on projects demonstrating the pivot.',
        'AI tools that differentiate the hybrid profile.',
      ],
      projects: [
        'Cross-functional programs bridging two disciplines.',
        'Prototype AI-enabled workflows with measurable outcomes.',
      ],
      earningsStrategy: [
        'Use outcome-based negotiation tied to unique skill combinations.',
        'Switch employers if growth opportunities stall.',
      ],
      examples: [
        'Add a verified real-world example with a source link.',
        'Example should include name, unconventional pivot, and outcome.',
      ],
      differentials: [
        'Compensation differential: 10-30 percent upside if pivot succeeds.',
        'Timeline differential: faster progression with higher learning intensity.',
        'Effort differential: high intensity during transition period.',
        'Optionality: opens new industries and hybrid roles.',
      ],
      aiResilience: 'Medium-high when positioned as AI + human expertise.',
    },
    {
      tier: 'Tier 3: Moonshot Path',
      title: 'AI-enabled entrepreneurial or executive leap',
      overview:
        'Pursue a high-upside path such as founding, AI leadership, or rapid executive growth.',
      riskReward: 'High risk, exponential potential.',
      earningPotential: 'Significant upside but uncertain outcomes.',
      threeYearPlan: {
        year1: [
          'Validate a market gap using rapid customer discovery.',
          'Build an MVP and secure early adopters.',
          'Create a 6-12 month financial runway.',
        ],
        year2: [
          'Scale distribution or partnerships.',
          'Build a small, high-leverage team.',
          'Establish product-market fit signals.',
        ],
        year3: [
          'Pursue funding or revenue scale depending on model.',
          'Expand into adjacent markets.',
        ],
      },
      fiveYearPlan: {
        year4: [
          'Decide on growth vs. profitability focus.',
          'Build leadership bench and operational resilience.',
        ],
        year5: [
          'Target founder, partner, or executive roles.',
          'Diversify income streams and de-risk exposure.',
        ],
      },
      learningPath: [
        'Founder skill set: sales, finance, legal, and go-to-market.',
        'AI strategy and data governance.',
        'Advisory network and mentor board.',
      ],
      projects: [
        'Pilot AI solution for a niche industry pain point.',
        'Build a thought leadership platform in the target space.',
      ],
      earningsStrategy: [
        'Focus on revenue quality and unit economics.',
        'Use equity strategically to attract talent.',
      ],
      examples: [
        'Add a verified real-world example with a source link.',
        'Example should include name, leap taken, and results.',
      ],
      differentials: [
        'Compensation differential: potentially 2x-10x but volatile.',
        'Timeline differential: faster upside if traction hits early.',
        'Effort differential: extreme intensity and ambiguity.',
        'Optionality: opens founder, investor, and advisory paths.',
      ],
      aiResilience: 'High if business is built around AI advantage.',
    },
  ];
};

const buildLearningRoadmap = (profile: UserProfile): ReportSection => {
  const gaps = [];
  if (profile.aiLiteracy === 'Beginner') {
    gaps.push('AI literacy and applied tooling');
  }
  if (profile.riskTolerance === 'Low') {
    gaps.push('Confidence in calculated risk-taking');
  }

  return {
    id: 'learning-roadmap',
    title: 'Competency-Based Learning Roadmap',
    summary: gaps.length
      ? `Priority gaps: ${gaps.join(', ')}.`
      : 'No critical gaps flagged; focus on applied projects and visibility.',
    bullets: [
      'Weeks 1-2: Core concepts using free resources with notes.',
      'Weeks 3-4: Build a small project showing real-world impact.',
      'Weeks 5-8: Apply the skill on a real stakeholder or client problem.',
      'Weeks 9-12: Publish a portfolio artifact or case study.',
      'Competency milestones: Beginner (guided), Competent (independent), Proficient (teaches), Expert (innovates).',
    ],
  };
};

const buildSkillsGapResources = (): ReportSection => ({
  id: 'skills-gap-resources',
  title: 'Market-Validated Learning Resources',
  summary: 'Only include credentials that employers recognize and pay for.',
  bullets: [
    ...MARKET_VALIDATED_RESOURCES.map(
      (resource) =>
        `${resource.name} - ${resource.url} - ${resource.cost} - ${resource.time} - ${resource.recognition}`
    ),
    `Low-cost options: ${LOW_COST_OPTIONS.join('; ')}`,
    `Formal education: ${FORMAL_EDUCATION_OPTIONS.join('; ')}`,
  ],
});

const buildCompetencyMilestones = (skills: SkillInsight[]): ReportSection => {
  const topSkills = skills.slice(0, 3);
  const salaryByCategory: Record<SkillCategory, string> = {
    technical: 'Beginner $70K | Competent $95K | Proficient $125K | Expert $160K+',
    analytical: 'Beginner $65K | Competent $85K | Proficient $110K | Expert $145K+',
    leadership: 'Beginner $80K | Competent $110K | Proficient $150K | Expert $200K+',
    creative: 'Beginner $55K | Competent $75K | Proficient $100K | Expert $130K+',
    'soft/interpersonal': 'Beginner $50K | Competent $70K | Proficient $95K | Expert $130K+',
    'domain-specific': 'Beginner $60K | Competent $85K | Proficient $115K | Expert $150K+',
  };

  return {
    id: 'competency-milestones',
    title: 'Competency Milestones',
    summary: 'Compensation increases with demonstrated competence, not tenure.',
    bullets: topSkills.length
      ? topSkills.map(
          (skill) => `${skill.name}: ${salaryByCategory[skill.category]} (example ranges)`
        )
      : ['Add skills to generate competency milestones.'],
  };
};

const buildProjectsToPursue = (): ReportSection => ({
  id: 'projects-to-pursue',
  title: 'Projects and Experiences to Pursue',
  summary: 'Projects should show measurable impact and AI-ready workflows.',
  bullets: [
    'Cross-functional initiatives tied to revenue, efficiency, or risk reduction.',
    'AI-augmented workflows with before/after metrics.',
    'High-visibility assignments with executive stakeholders.',
    'Volunteer or side projects that fill resume gaps.',
  ],
});

const buildEarningsMaximization = (): ReportSection => ({
  id: 'earnings-maximization',
  title: 'Earnings Maximization Strategy',
  summary: 'Compensation growth is driven by timing and proof of impact.',
  bullets: [
    'Negotiate at moments of leverage: promotions, offers, or strategic wins.',
    'Use total compensation optimization (equity, bonus, benefits).',
    'Consider geographic arbitrage via remote roles.',
    'Build multiple income streams (consulting, teaching, content).',
  ],
});

const buildOpportunityMap = (): ReportSection => ({
  id: 'opportunity-map',
  title: 'Opportunity Map',
  summary: 'Balance traditional roles with AI-enabled entrepreneurship.',
  bullets: [
    'Traditional roles with strong AI resilience.',
    'Emerging AI roles that amplify existing skills.',
    'Consulting or freelance paths for specialized expertise.',
    'AI-powered business ideas aligned with industry gaps.',
  ],
});

const buildGapAnalysis = (profile: UserProfile, skills: SkillInput[]): ReportSection => {
  const gaps = [];
  if (!profile.age || !profile.gender || !profile.raceEthnicity) {
    gaps.push('Complete demographic inputs for tailored guidance.');
  }
  if (skills.length === 0) gaps.push('Add at least 5-10 skills for ranking.');
  if (!profile.location) gaps.push('Add location to tailor geographic strategy.');
  if (!profile.aiLiteracy) gaps.push('Specify AI literacy level.');

  return {
    id: 'gap-analysis',
    title: 'Gap Analysis',
    summary: gaps.length ? 'Critical gaps detected.' : 'No critical gaps detected.',
    bullets: gaps.length
      ? gaps
      : ['Continue refining skills and market data for higher precision.'],
  };
};

const buildGeographicOptions = (profile: UserProfile): ReportSection => ({
  id: 'geographic-options',
  title: 'Multi-Geographic Job Search Strategy',
  summary: 'Explore opportunities across local, regional, national, and international markets.',
  bullets: [
    `Local: roles within commuting distance of ${profile.location || 'your location'}.`,
    'Regional: expand to the broader metro or state region.',
    'National: remote-friendly roles with competitive pay bands.',
    'International: global remote roles or relocation opportunities.',
  ],
});

const buildInternationalPlan = (): ReportSection => ({
  id: 'international-plan',
  title: 'International Transition Plan',
  summary: 'Plan visa, financial, and cultural integration steps before moving.',
  bullets: [
    'Research visa pathways (skilled worker, employer-sponsored, entrepreneur).',
    'Compare cost of living and salary expectations.',
    'Prepare 3, 6, and 12 month relocation timelines.',
    'Document credential transfer requirements.',
    'Build local professional networks before moving.',
  ],
});

const buildEntrepreneurshipPlan = (): ReportSection => ({
  id: 'entrepreneurship-plan',
  title: 'Employee-to-Entrepreneur Transition Plan',
  summary: 'Build runway, validate demand, and reduce downside risk.',
  bullets: [
    'Save 6-12 months of living expenses.',
    'Validate the idea with an MVP while employed.',
    'Set up legal structure, taxes, and insurance.',
    'Build first customer pipeline before quitting.',
    'Track key metrics and set pivot criteria.',
  ],
});

const buildActionPlan = (): ReportSection => ({
  id: 'action-plan',
  title: 'Action Plan',
  summary: 'Prioritized next steps with timelines.',
  bullets: [
    'Week 1: Complete full assessment and market snapshot.',
    'Week 2: Validate top skills with evidence and outcomes.',
    'Week 3-4: Build one AI-augmented portfolio project.',
    'Month 2: Expand network outreach and target roles.',
    'Month 3: Apply to roles and run structured interview prep.',
  ],
});

const buildMarketOutlook = (): ReportSection => ({
  id: 'market-outlook',
  title: 'Market Outlook and Projections',
  summary: 'Use BLS, LinkedIn Workforce Reports, and WEF data to verify trends.',
  bullets: [
    'Check BLS Occupational Outlook Handbook for 10-year growth projections.',
    'Compare LinkedIn skills demand and industry hiring signals.',
    'Review AI impact studies (McKinsey, Goldman Sachs, OpenAI research).',
    'Track job posting volume for target roles monthly.',
  ],
});

const buildCareerInsights = (profile: UserProfile): ReportSection => ({
  id: 'career-insights',
  title: 'Comprehensive Career Insights',
  summary: 'Blend company, industry, role, market, and future outlook intelligence.',
  bullets: [
    'Company analysis: revenue health, layoffs/expansions, AI strategy, compensation philosophy.',
    'Industry analysis: growth stage, regulatory shifts, funding and M&A activity.',
    'Role analysis: clear ladders, skill differentiators by level, AI task automation impacts.',
    'Market analysis: geographic hotspots, remote prevalence, supply/demand signals.',
    `Future outlook: 3-5-10 year projections with AI impact for ${profile.currentRole || 'target roles'}.`,
    'Compensation ranges: Entry $X-$Y, Mid $X-$Y, Senior $X-$Y, Lead $X-$Y, Director $X-$Y.',
  ],
});

export const generateCipherReport = (
  profile: UserProfile,
  skills: SkillInput[],
  market: MarketSnapshot,
  connections: LinkedInConnection[]
): CipherReport => {
  const skillInsights = skills.map(buildSkillInsight);
  const rankedSkills = [...skillInsights].sort(
    (a, b) => b.marketValueScore - a.marketValueScore
  );

  const safeSkills = rankedSkills.filter(
    (skill) => skill.aiRisk === 'Very Low' || skill.aiRisk === 'Low'
  );
  const atRiskSkills = rankedSkills.filter(
    (skill) => skill.aiRisk === 'High' || skill.aiRisk === 'Very High'
  );

  const aiResilience: ReportSection = {
    id: 'ai-resilience',
    title: 'AI Resilience Assessment',
    summary: 'Cipher flags which skills are safest, at risk, or opportunity areas.',
    bullets: [
      safeSkills.length
        ? `AI-resistant skills: ${safeSkills.map((skill) => skill.name).join(', ')}.`
        : 'AI-resistant skills: Add more leadership or relational skills.',
      atRiskSkills.length
        ? `At-risk skills: ${atRiskSkills.map((skill) => skill.name).join(', ')}.`
        : 'At-risk skills: No high-risk skills detected.',
      `AI-resistant characteristics: ${AI_RESISTANT_CHARACTERISTICS.join('; ')}`,
    ],
  };

  const report: CipherReport = {
    marketSnapshot: buildMarketSnapshot(market),
    skillsPortfolio: rankedSkills.slice(0, 10),
    aiResilience,
    aiForward: buildAIForward(skills, profile.careerGoals),
    demographicStrategy: buildDemographicStrategy(profile),
    careerInsights: buildCareerInsights(profile),
    careerPaths: buildCareerPaths(profile, rankedSkills),
    learningRoadmap: buildLearningRoadmap(profile),
    skillsGapResources: buildSkillsGapResources(),
    competencyMilestones: buildCompetencyMilestones(rankedSkills),
    projectsToPursue: buildProjectsToPursue(),
    earningsMaximization: buildEarningsMaximization(),
    opportunityMap: buildOpportunityMap(),
    gapAnalysis: buildGapAnalysis(profile, skills),
    geographicOptions: buildGeographicOptions(profile),
    internationalPlan: profile.openToInternational ? buildInternationalPlan() : undefined,
    entrepreneurshipPlan: profile.careerGoals.includes('Entrepreneurship')
      ? buildEntrepreneurshipPlan()
      : undefined,
    actionPlan: buildActionPlan(),
    marketOutlook: buildMarketOutlook(),
    networkReport: connections.length ? buildNetworkReport(connections) : undefined,
  };

  return report;
};
